### ISSUE TITLE
Uncaught Error: Cannot find module 'meteor/communitypackages:autoform-booostrap4/static'

### ISSUE THREAD

**Issue by DavidGasku** [Meteor-Community-Packages/meteor-autoform-themes#1]
when imported like this:

import { AutoFormThemeBootstrap4 } from 'meteor/communitypackages:autoform-booostrap4/static'

It could be my mistake, but the same line works with **autoform-plain**

**Comment by jankapunkt** [comment]
Hi @DavidGasku can you please describe the issue a bit more? Did you encounter a bug or unexpected behavior?

**Comment by DavidGasku** [comment]
Damn, there is a typo in the documentation xD. I feel ashamed I didn't notice, last time I copy&paste.

It is in this line:
import { AutoFormThemeBootstrap4 } from 'meteor/communitypackages:autoform-**booostrap4**/dynamic'

notice the 3 o's

**Comment by jankapunkt** [comment]
@DavidGasku  no need to feel bad about yourself, in the end it was my mistake to not carefully reading the documentation before publishing it.

**Comment by lynchem** [comment]
There's still some typooos in the bs3 install guide @jankapunkt  - I'm just getting around to adding AF7 to a beta ;-)

**Comment by jankapunkt** [comment]
@lynchem thanks a lot for the hint, fixed it together with https://github.com/Meteor-Community-Packages/meteor-autoform-themes/pull/2 and merged
