### ISSUE TITLE
Add Bootstrap 5 theme

### ISSUE THREAD

**Issue by jankapunkt** [Meteor-Community-Packages/meteor-autoform-themes#4]
Bootstrap 5 is in beta2 and will soon be in RC stage. There won't be many changes to be expected so we could already start with a theme skeleton. Support from early adopters is highly appreciated.

**Comment by ferjep** [comment]
`select` fields are missing "form-select" class, causing them to not render the arrow down on the right

**Comment by jankapunkt** [comment]
Thanks for the hin @ferjep would you mind opening a PR where this is added? I will review and publish asap
