### ISSUE TITLE
Cannot Find Module

### ISSUE THREAD

**Issue by fillipefeitosa** [Meteor-Community-Packages/meteor-autoform-themes#6]
Hello, Thanks for the amazing effort to make this available.

I just updated to autoform 7.0.0, and after following the installation docs I get a blank form, no server errors. Browser console gives me the error:
```
Uncaught Error: Cannot find module 'meteor/communitypackages:autoform-boostrap4/static'
``` 

I am aware of the [typo problem](https://github.com/Meteor-Community-Packages/meteor-autoform-themes/issues/1), but does seem the case.

Here is my code on _app/client/main.js_

```

// communitypackages:autoform-bootstrap4
import "bootstrap";
import "bootstrap/dist/css/bootstrap.css"; // optional, default theme
import "@fortawesome/fontawesome-free/js/all.js"; // optional, is using FA5
import popper from "popper.js";
global.Popper = popper;


import { AutoFormThemeBootstrap4 } from "meteor/communitypackages:autoform-boostrap4/static"; // This is the line that raises the error
AutoFormThemeBootstrap4.load();
AutoForm.setDefaultTemplate("bootstrap4");

``` 

If you could help me with any insights, I would be much appreciated. 

And just to make sure, this is my packages:

```
aldeed:collection2@3.0.0
aldeed:autoform@7.0.0!
aldeed:template-extension
msavin:mongol
momentjs:moment
accounts-ui@1.4.2
accounts-password@2.2.0
raix:handlebar-helpers
msavin:jetsetter
alanning:roles
dburles:mongo-collection-instances
dburles:collection-helpers
fortawesome:fontawesome
jquery@3.0.0!
communitypackages:autoform-bootstrap4
```

**Comment by jankapunkt** [comment]
Please try

```
import { AutoFormThemeBootstrap4 } from "meteor/communitypackages:autoform-bootstrap4/static";
```

**Comment by fillipefeitosa** [comment]
Thanks for the response.

My _app/client/main.js_ already had this line, but I copy and paste just to make sure, no success.

As a test, I also installed the _Plain Theme_, replaced with the proper code (as follows) and it worked. But the bootstrap 4 still not working. I need the v4 to keep consistency with the rest of the site. 

```
import { AutoFormPlainTheme } from "meteor/communitypackages:autoform-plain/static";
AutoFormPlainTheme.load();
AutoForm.setDefaultTemplate("plain");
```

**Comment by alfazjikani** [comment]
> Add-on Package Authors: Please test your package against AutoForm 7.0, and then release a major version update in which you change your api.use to api.use('aldeed:autoform@7.0.0');. We do NOT recommend using something like api.use('aldeed:autoform@6.0.0 || 7.0.0'); to try to support multiple major versions of AutoForm because there is currently a known Meteor issue where trying to support too many dependency paths leads to running out of memory when trying to resolve dependencies.

I found below code in package.js file. It may be issue.
api.use('aldeed:autoform@6.0.0 || 7.0.0');

**Comment by alfazjikani** [comment]
@fillipefeitosa  There is typo in documentation.
import { AutoFormThemeBootstrap4 } from "meteor/communitypackages:autoform-**boostrap4**/dynamic";

import { AutoFormThemeBootstrap4 } from "meteor/communitypackages:autoform-**bootstrap4**/dynamic";

**Comment by fillipefeitosa** [comment]
Hey friend, thanks for the response.

If you check my first post, my code already corrected the typo. I also copied and paste your suggestion just to make sure.

```
# client/main.js
import { AutoFormThemeBootstrap4 } from "meteor/communitypackages:autoform-bootstrap4/static";
AutoFormThemeBootstrap4.load();
AutoForm.setDefaultTemplate("bootstrap4");
```


Gives me the console error:
```
Uncaught Error: Cannot find module 'meteor/communitypackages:autoform-bootstrap4/static'
```

**Comment by jankapunkt** [comment]
@fillipefeitosa can you please check in your versions file, that you really have `communitypackages:autoform-bootstrap4` installed with version `1.0.5` ?

**Comment by fillipefeitosa** [comment]
Thanks for your time and attention.

Indeed, the version was 1.0.4

after the update it is working perfectly.
